# Generated by Django 5.2.8 on 2025-12-06 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='emoji',
            field=models.CharField(choices=[('😀', '😀'), ('🙂', '🙂'), ('😐', '😐'), ('😢', '😢'), ('😡', '😡'), ('😴', '😴')], max_length=10),
        ),
    ]
