# Generated by Django 5.2.8 on 2025-12-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emoji', '0002_alter_mood_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
